### ISSUE TITLE
Too many midi devices without a name

### ISSUE THREAD

**Issue by jibundeyare** [Marzac/OPA-Editor#6]
When I click on "Menu > Connection", I see the Arduino ports but for midi ports I just get a list of 64 entries of "Midi on:" without any name and the expected virtual midi devices are not shown.

Bu when I list all midi devices I get this list:
```
$ aconnect -l
client 0: 'System' [type=noyau]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=noyau]
    0 'Midi Through Port-0'
client 24: 'Virtual Raw MIDI 2-0' [type=noyau,card=2]
    0 'VirMIDI 2-0     '
client 25: 'Virtual Raw MIDI 2-1' [type=noyau,card=2]
    0 'VirMIDI 2-1     '
client 26: 'Virtual Raw MIDI 2-2' [type=noyau,card=2]
    0 'VirMIDI 2-2     '
client 27: 'Virtual Raw MIDI 2-3' [type=noyau,card=2]
    0 'VirMIDI 2-3     '

```
And when using giada, kimidimon or qtractor I can also see the virtual midi devices.

For your information, I am using archlinux and I have qt5 installed (or at least most of the components).
```
$ yaourt -Qs qt5
extra/attica-qt5 5.27.0-1 (kf5)
    Qt5 library that implements the Open Collaboration Services API
community/drumstick 1.0.2-2
    MIDI libraries for Qt5/C++
extra/libdbusmenu-qt5 0.9.3+16.04.20160218-1
    A library that provides a Qt implementation of the DBusMenu spec
extra/phonon-qt5 4.9.0-1
    The multimedia framework for KF5
extra/phonon-qt5-gstreamer 4.9.0-1
    Phonon GStreamer backend for Qt5
extra/polkit-qt5 0.112.0+git20160226-1
    A library that allows developers to access PolicyKit API with a nice Qt-style API
extra/poppler-qt5 0.47.0-1
    Poppler Qt5 bindings
extra/qt5-base 5.7.0-3 (qt qt5)
    A cross-platform application and UI framework
extra/qt5-declarative 5.7.0-3 (qt qt5)
    Classes for QML and JavaScript languages
extra/qt5-location 5.7.0-1 (qt qt5)
    Provides access to position, satellite and area monitoring classes
extra/qt5-multimedia 5.7.0-1 (qt qt5)
    Classes for audio, video, radio and camera functionality
extra/qt5-script 5.7.0-1 (qt qt5)
    Classes for making Qt applications scriptable. Provided for Qt 4.x compatibility
extra/qt5-sensors 5.7.0-1 (qt qt5)
    Provides access to sensor hardware and motion gesture recognition
extra/qt5-svg 5.7.0-1 (qt qt5)
    Classes for displaying the contents of SVG files
extra/qt5-tools 5.7.0-2 (qt qt5)
    A cross-platform application and UI framework (Development Tools, QtHelp)
extra/qt5-webchannel 5.7.0-1 (qt qt5)
    Provides access to QObject or QML objects from HTML clients for seamless integration of Qt applications with 
    HTML/JavaScript clients
extra/qt5-webkit 5.7.0-1 (qt qt5)
    Classes for a WebKit2 based implementation and a new QML API
extra/qt5-x11extras 5.7.0-1 (qt qt5)
    Provides platform-specific APIs for X11
extra/qt5-xmlpatterns 5.7.0-2 (qt qt5)
    Support for XPath, XQuery, XSLT and XML schema validation
extra/sonnet 5.27.0-1 (kf5)
    Spelling framework for Qt5
```
I don't have a clue as to what is going wrong. Any help would be much appreciated!

**Comment by jibundeyare** [comment]
Hi @Marzac.

I made a little test program to understand what was going on:

```
#include <iostream>

#include "midi/midiin.h"

main()
{
    int portNb;

    // Enumerate MIDI devices
    portNb = MidiIn::getNoDevices();

    std::cout << std::endl;

    for (int i = 0; i < portNb; i++) {
        std::cout << "Midi device " << i << ": " << MidiIn::getDeviceInName(i);
        std::cout << std::endl;
        std::cout << std::endl;
    }

    return 0;
}
```

And built it this way:

```
qmake . && make -j 4 && g++ -c test.cpp && g++ -o test test.o midiin-linux.o -lasound -lpthread && ./test
```

When run, I got the result:

```
Midi device 0: 

Midi device 1: 

Midi device 2: 

[...]
Midi device 63: 

```

This looks like there's a confusion between midi devices and midi channels (4 virtual midi devices * 16 channels == 64).

I also tried to understand how `midi/midiin-linux.cpp` works by adding a few `printf()` calls. This showed me clearly that `subDevice` was counting midi channels. Is that the way it was intended ?

I also tried to run a minimal sketch to see if the board could make any sound:
```
#include <OPA.h>

OPA opa;

void setup() {
  opa.enable();
  opa.loadInternal(OPA_PROGRAM_0, 0); 
}

void loop() {
  int p1 = 512 >> 2;
  opa.writeOperatorParam(OPA_PROGRAM_0, OPA_OPERATOR_1, OPA_OP_VOLUME, p1);

  opa.noteOn(OPA_PROGRAM_0, 60);
  delay(1000);

  opa.noteOff(OPA_PROGRAM_0, 60);
  delay(1000);
}
```

But this was also a failure. I can see a led blinking on the arduino telling me the sketch works but there's no sound coming out of the shield (which was connected to an amplifier, not a headphone).

I'm feeling like a real noob, which is what I am in this field.

Any help much grealty appreciated !

**Comment by Marzac** [comment]
Bonjour,

thank you for your message. Here are two problems.

1) No sound from shield
opa.loadInternal(OPA_PROGRAM_0, 0); 
Don't load a preset if there is no preset stored in the internal memory!
Rather use the default preset = do not load anything.

2) Bad MIDI enumeration
I have tested the editor on my Linux machine and there are actually other users
working with it on Linux on different Linux distributions. So there is something 
different with your specific configuration.

Remember the enumeration is made for "rawmidi" devices which are actual
hardware devices no virtual ports. I've had a look at the code again and see
nothing wrong (to my knowledge) here. Since you have all the debug environ-
ment installed and your configuration makes a problem try to debug it by listing
all devices name reported by Alsa. But this problem is very suspicious to me

Frederic

**Comment by Marzac** [comment]
I cannot easily reproduce the problem here so I cannot help you much. If other users have the same problem, please report it so I can try to understand it.

**Comment by jibundeyare** [comment]
Hi @Marzac.

What I completely forgot to mention that I was also unable to get any sound from the shield.

But it appears that the problem of the numerous midi ports and the problem of getting no sound were completely unrelated.

I created a new issue about the "no sound" problem #7.

I still see far too many midi ports (in fact all channels for every port) but now I do have sound.

**Comment by jibundeyare** [comment]
Closing this as I think it is finally a non issue.
