### ISSUE TITLE
Can't get any sound from the shield

### ISSUE THREAD

**Issue by jibundeyare** [Marzac/OPA-Editor#7]
Connecting the shield out of the box and using the fm minimum program does not generate any sound.

**Comment by jibundeyare** [comment]
I had skipped the *RTFM* step.

My problem with getting the sound was that I did not remove the jumper that was connected to J1 from the shield. Thus the shield was expecting serial data from DIG2 and not from DIG1.

So to get sound from the shield I removed the jumper that was connected to J1 and used the default FM minimal sketch from your memo card.

**Comment by Marzac** [comment]
Hi,
> I had skipped the RTFM step.

-> You said it ;-)
I hope you're enjoying making sounds with your shield now.
